#encoding: utf-8

class CreateCountries < ActiveRecord::Migration

  def self.up
    create_table :countries, :force => true do |t|
      t.column :name, :string
      t.column :value, :string, :limit => 3
      t.column :cached_slug, :string
      t.column :site_id, :integer
      t.timestamps
    end

    @site = Site.first
  
    Country.create(:name => "Afganistán", :value => "AF", :site_id => @site.id)
    Country.create(:name => "Albania", :value => "AL", :site_id => @site.id)
    Country.create(:name => "Argelia", :value => "DZ", :site_id => @site.id)
    Country.create(:name => "Samoa Americana", :value => "AS", :site_id => @site.id)
    Country.create(:name => "Andorra", :value => "AD", :site_id => @site.id)
    Country.create(:name => "Angola", :value => "AO", :site_id => @site.id)
    Country.create(:name => "Anguilla", :value => "AI", :site_id => @site.id)
    Country.create(:name => "Antártida", :value => "AQ", :site_id => @site.id)
    Country.create(:name => "Antigua y Barbuda", :value => "AG", :site_id => @site.id)
    Country.create(:name => "Argentina", :value => "AR", :site_id => @site.id)
    Country.create(:name => "Armenia", :value => "AM", :site_id => @site.id)
    Country.create(:name => "Aruba", :value => "AW", :site_id => @site.id)
    Country.create(:name => "Australia", :value => "AU", :site_id => @site.id)
    Country.create(:name => "Austria", :value => "AT", :site_id => @site.id)
    Country.create(:name => "Azerbaiyán", :value => "AZ", :site_id => @site.id)
    Country.create(:name => "Bahamas", :value => "BS", :site_id => @site.id)
    Country.create(:name => "Bahrein", :value => "BH", :site_id => @site.id)
    Country.create(:name => "Bangladesh", :value => "BD", :site_id => @site.id)
    Country.create(:name => "Barbados", :value => "BB", :site_id => @site.id)
    Country.create(:name => "Bielorrusia", :value => "BY", :site_id => @site.id)
    Country.create(:name => "Bélgica", :value => "BE", :site_id => @site.id)
    Country.create(:name => "Belice", :value => "BZ", :site_id => @site.id)
    Country.create(:name => "Benin", :value => "BJ", :site_id => @site.id)
    Country.create(:name => "Bermudas", :value => "BM", :site_id => @site.id)
    Country.create(:name => "Bután", :value => "BT", :site_id => @site.id)
    Country.create(:name => "Bolivia", :value => "BO", :site_id => @site.id)
    Country.create(:name => "Bosnia y Herzegovina", :value => "BA", :site_id => @site.id)
    Country.create(:name => "Botswana", :value => "BW", :site_id => @site.id)
    Country.create(:name => "Isla Bouvet", :value => "BV", :site_id => @site.id)
    Country.create(:name => "Brasil", :value => "BR", :site_id => @site.id)
    Country.create(:name => "Territorios británicos del océano Índico", :value => "IO", :site_id => @site.id)
    Country.create(:name => "Brunei", :value => "BN", :site_id => @site.id)
    Country.create(:name => "Bulgaria", :value => "BG", :site_id => @site.id)
    Country.create(:name => "Burkina Faso", :value => "BF", :site_id => @site.id)
    Country.create(:name => "Burundi", :value => "BI", :site_id => @site.id)
    Country.create(:name => "Camboya", :value => "KH", :site_id => @site.id)
    Country.create(:name => "Camerún", :value => "CM", :site_id => @site.id)
    Country.create(:name => "Canadá", :value => "CA", :site_id => @site.id)
    Country.create(:name => "Cabo Verde", :value => "CV", :site_id => @site.id)
    Country.create(:name => "Islas Caimán", :value => "KY", :site_id => @site.id)
    Country.create(:name => "República Centroafricana", :value => "CF", :site_id => @site.id)
    Country.create(:name => "Chad", :value => "TD", :site_id => @site.id)
    Country.create(:name => "Chile", :value => "CL", :site_id => @site.id)
    Country.create(:name => "China", :value => "CN", :site_id => @site.id)
    Country.create(:name => "Isla de Christmas", :value => "CX", :site_id => @site.id)
    Country.create(:name => "Islas de Cocos o Keeling", :value => "CC", :site_id => @site.id)
    Country.create(:name => "Colombia", :value => "CO", :site_id => @site.id)
    Country.create(:name => "Comores", :value => "KM", :site_id => @site.id)
    Country.create(:name => "Congo", :value => "CG", :site_id => @site.id)
    Country.create(:name => "Congo, República Democrática del", :value => "CD", :site_id => @site.id)
    Country.create(:name => "Islas Cook", :value => "CK", :site_id => @site.id)
    Country.create(:name => "Costa Rica", :value => "CR", :site_id => @site.id)
    Country.create(:name => "Costa de Marfíl", :value => "CI", :site_id => @site.id)
    Country.create(:name => "Croacia", :value => "HR", :site_id => @site.id)
    Country.create(:name => "Cuba", :value => "CU", :site_id => @site.id)
    Country.create(:name => "Chipre", :value => "CY", :site_id => @site.id)
    Country.create(:name => "República Checa", :value => "CZ", :site_id => @site.id)
    Country.create(:name => "Dinamarca", :value => "DK", :site_id => @site.id)
    Country.create(:name => "Djibouti", :value => "DJ", :site_id => @site.id)
    Country.create(:name => "Dominica", :value => "DM", :site_id => @site.id)
    Country.create(:name => "República Dominicana", :value => "DO", :site_id => @site.id)
    Country.create(:name => "Timor Oriental", :value => "TP", :site_id => @site.id)
    Country.create(:name => "Ecuador", :value => "EC", :site_id => @site.id)
    Country.create(:name => "Egipto", :value => "EG", :site_id => @site.id)
    Country.create(:name => "El Salvador", :value => "SV", :site_id => @site.id)
    Country.create(:name => "Guinea Ecuatorial", :value => "GQ", :site_id => @site.id)
    Country.create(:name => "Eritrea", :value => "ER", :site_id => @site.id)
    Country.create(:name => "Estonia", :value => "EE", :site_id => @site.id)
    Country.create(:name => "Etiopía", :value => "ET", :site_id => @site.id)
    Country.create(:name => "Islas Malvinas", :value => "FK", :site_id => @site.id)
    Country.create(:name => "Islas Faroe", :value => "FO", :site_id => @site.id)
    Country.create(:name => "Fiji", :value => "FJ", :site_id => @site.id)
    Country.create(:name => "Finlandia", :value => "FI", :site_id => @site.id)
    Country.create(:name => "Francia", :value => "FR", :site_id => @site.id)
    Country.create(:name => "Guayana Francesa", :value => "GF", :site_id => @site.id)
    Country.create(:name => "Polinesia Francesa", :value => "PF", :site_id => @site.id)
    Country.create(:name => "Territorios franceses del Sur", :value => "TF", :site_id => @site.id)
    Country.create(:name => "Gabón", :value => "GA", :site_id => @site.id)
    Country.create(:name => "Gambia", :value => "GM", :site_id => @site.id)
    Country.create(:name => "Georgia", :value => "GE", :site_id => @site.id)
    Country.create(:name => "Alemania", :value => "DE", :site_id => @site.id)
    Country.create(:name => "Ghana", :value => "GH", :site_id => @site.id)
    Country.create(:name => "Gibraltar", :value => "GI", :site_id => @site.id)
    Country.create(:name => "Grecia", :value => "GR", :site_id => @site.id)
    Country.create(:name => "Groenlandia", :value => "GL", :site_id => @site.id)
    Country.create(:name => "Granada", :value => "GD", :site_id => @site.id)
    Country.create(:name => "Guadalupe", :value => "GP", :site_id => @site.id)
    Country.create(:name => "Guam", :value => "GU", :site_id => @site.id)
    Country.create(:name => "Guatemala", :value => "GT", :site_id => @site.id)
    Country.create(:name => "Guinea", :value => "GN", :site_id => @site.id)
    Country.create(:name => "Guinea-Bissau", :value => "GW", :site_id => @site.id)
    Country.create(:name => "Guayana", :value => "GY", :site_id => @site.id)
    Country.create(:name => "Haití", :value => "HT", :site_id => @site.id)
    Country.create(:name => "Islas Heard y McDonald", :value => "HM", :site_id => @site.id)
    Country.create(:name => "Honduras", :value => "HN", :site_id => @site.id)
    Country.create(:name => "Hong Kong", :value => "HK", :site_id => @site.id)
    Country.create(:name => "Hungría", :value => "HU", :site_id => @site.id)
    Country.create(:name => "Islandia", :value => "IS", :site_id => @site.id)
    Country.create(:name => "India", :value => "IN", :site_id => @site.id)
    Country.create(:name => "Indonesia", :value => "ID", :site_id => @site.id)
    Country.create(:name => "Irán", :value => "IR", :site_id => @site.id)
    Country.create(:name => "Irak", :value => "IQ", :site_id => @site.id)
    Country.create(:name => "Irlanda", :value => "IE", :site_id => @site.id)
    Country.create(:name => "Israel", :value => "IK", :site_id => @site.id)
    Country.create(:name => "Italia", :value => "IT", :site_id => @site.id)
    Country.create(:name => "Jamaica", :value => "JM", :site_id => @site.id)
    Country.create(:name => "Japón", :value => "JP", :site_id => @site.id)
    Country.create(:name => "Jordania", :value => "JO", :site_id => @site.id)
    Country.create(:name => "Kazajistán", :value => "KZ", :site_id => @site.id)
    Country.create(:name => "Kenia", :value => "KE", :site_id => @site.id)
    Country.create(:name => "Kiribati", :value => "KI", :site_id => @site.id)
    Country.create(:name => "Corea", :value => "KR", :site_id => @site.id)
    Country.create(:name => "Corea del Norte", :value => "KP", :site_id => @site.id)
    Country.create(:name => "Kuwait", :value => "KW", :site_id => @site.id)
    Country.create(:name => "Kirguizistán", :value => "KG", :site_id => @site.id)
    Country.create(:name => "Laos", :value => "LA", :site_id => @site.id)
    Country.create(:name => "Letonia", :value => "LV", :site_id => @site.id)
    Country.create(:name => "Líbano", :value => "LB", :site_id => @site.id)
    Country.create(:name => "Lesotho", :value => "LS", :site_id => @site.id)
    Country.create(:name => "Liberia", :value => "LR", :site_id => @site.id)
    Country.create(:name => "Libia", :value => "LY", :site_id => @site.id)
    Country.create(:name => "Liechtenstein", :value => "LI", :site_id => @site.id)
    Country.create(:name => "Lituania", :value => "LT", :site_id => @site.id)
    Country.create(:name => "Luxemburgo", :value => "LI", :site_id => @site.id)
    Country.create(:name => "Macao", :value => "MO", :site_id => @site.id)
    Country.create(:name => "Madagascar", :value => "MG", :site_id => @site.id)
    Country.create(:name => "Malawi", :value => "MW", :site_id => @site.id)
    Country.create(:name => "Malasia", :value => "MY", :site_id => @site.id)
    Country.create(:name => "Maldivas", :value => "MV", :site_id => @site.id)
    Country.create(:name => "Malí", :value => "ML", :site_id => @site.id)
    Country.create(:name => "Islas Marshall", :value => "MT", :site_id => @site.id)
    Country.create(:name => "Martinica", :value => "MQ", :site_id => @site.id)
    Country.create(:name => "Mauritania", :value => "MR", :site_id => @site.id)
    Country.create(:name => "Mauricio", :value => "MU", :site_id => @site.id)
    Country.create(:name => "Mayotte", :value => "YT", :site_id => @site.id)
    Country.create(:name => "México", :value => "MX", :site_id => @site.id)
    Country.create(:name => "Micronesia", :value => "FM", :site_id => @site.id)
    Country.create(:name => "Moldavia", :value => "MD", :site_id => @site.id)
    Country.create(:name => "Mónaco", :value => "MC", :site_id => @site.id)
    Country.create(:name => "Mongolia", :value => "MN", :site_id => @site.id)
    Country.create(:name => "Montserrat", :value => "MS", :site_id => @site.id)
    Country.create(:name => "Marruecos", :value => "MA", :site_id => @site.id)
    Country.create(:name => "Mozambique", :value => "MZ", :site_id => @site.id)
    Country.create(:name => "Birmania", :value => "MM", :site_id => @site.id)
    Country.create(:name => "Namibia", :value => "NA", :site_id => @site.id)
    Country.create(:name => "Nauru", :value => "NR", :site_id => @site.id)
    Country.create(:name => "Nepal", :value => "NP", :site_id => @site.id)
    Country.create(:name => "Antillas Holandesas", :value => "AN", :site_id => @site.id)
    Country.create(:name => "Países Bajos", :value => "NL", :site_id => @site.id)
    Country.create(:name => "Nueva Caledonia", :value => "NC", :site_id => @site.id)
    Country.create(:name => "Nueva Zelanda", :value => "NZ", :site_id => @site.id)
    Country.create(:name => "Nicaragua", :value => "NI", :site_id => @site.id)
    Country.create(:name => "Níger", :value => "NE", :site_id => @site.id)
    Country.create(:name => "Nigeria", :value => "NG", :site_id => @site.id)
    Country.create(:name => "Niue", :value => "NU", :site_id => @site.id)
    Country.create(:name => "Norfolk", :value => "NF", :site_id => @site.id)
    Country.create(:name => "Islas Marianas del Norte", :value => "MP", :site_id => @site.id)
    Country.create(:name => "Noruega", :value => "NO", :site_id => @site.id)
    Country.create(:name => "Omán", :value => "OM", :site_id => @site.id)
    Country.create(:name => "Paquistán", :value => "PK", :site_id => @site.id)
    Country.create(:name => "Islas Palau", :value => "PW", :site_id => @site.id)
    Country.create(:name => "Panamá", :value => "PA", :site_id => @site.id)
    Country.create(:name => "Papúa Nueva Guinea", :value => "PG", :site_id => @site.id)
    Country.create(:name => "Paraguay", :value => "PY", :site_id => @site.id)
    Country.create(:name => "Perú", :value => "PE", :site_id => @site.id)
    Country.create(:name => "Filipinas", :value => "PH", :site_id => @site.id)
    Country.create(:name => "Pitcairn", :value => "PN", :site_id => @site.id)
    Country.create(:name => "Polonia", :value => "PL", :site_id => @site.id)
    Country.create(:name => "Portugal", :value => "PT", :site_id => @site.id)
    Country.create(:name => "Puerto Rico", :value => "PR", :site_id => @site.id)
    Country.create(:name => "Qatar", :value => "QA", :site_id => @site.id)
    Country.create(:name => "Reunión", :value => "RE", :site_id => @site.id)
    Country.create(:name => "Rumania", :value => "RO", :site_id => @site.id)
    Country.create(:name => "Rusia", :value => "RU", :site_id => @site.id)
    Country.create(:name => "Ruanda", :value => "RW", :site_id => @site.id)
    Country.create(:name => "Santa Helena", :value => "SH", :site_id => @site.id)
    Country.create(:name => "Saint Kitts y Nevis", :value => "KN", :site_id => @site.id)
    Country.create(:name => "Santa Lucía", :value => "LC", :site_id => @site.id)
    Country.create(:name => "St. Pierre y Miquelon", :value => "PM", :site_id => @site.id)
    Country.create(:name => "San Vicente y Granadinas", :value => "VC", :site_id => @site.id)
    Country.create(:name => "Samoa", :value => "WS", :site_id => @site.id)
    Country.create(:name => "San Marino", :value => "SM", :site_id => @site.id)
    Country.create(:name => "Santo Tomé y Príncipe", :value => "ST", :site_id => @site.id)
    Country.create(:name => "Arabia Saudí", :value => "SA", :site_id => @site.id)
    Country.create(:name => "Senegal", :value => "SN", :site_id => @site.id)
    Country.create(:name => "Seychelles", :value => "SC", :site_id => @site.id)
    Country.create(:name => "Sierra Leona", :value => "SL", :site_id => @site.id)
    Country.create(:name => "Singapur", :value => "SG", :site_id => @site.id)
    Country.create(:name => "República Eslovaca", :value => "SK", :site_id => @site.id)
    Country.create(:name => "Eslovenia", :value => "SI", :site_id => @site.id)
    Country.create(:name => "Islas Salomón", :value => "SB", :site_id => @site.id)
    Country.create(:name => "Somalia", :value => "SO", :site_id => @site.id)
    Country.create(:name => "República de Sudáfrica", :value => "ZA", :site_id => @site.id)
    Country.create(:name => "España", :value => "ES", :site_id => @site.id)
    Country.create(:name => "Sri Lanka", :value => "LK", :site_id => @site.id)
    Country.create(:name => "Sudán", :value => "SD", :site_id => @site.id)
    Country.create(:name => "Surinam", :value => "SR", :site_id => @site.id)
    Country.create(:name => "Islas Svalbard y Jan Mayen", :value => "SJ", :site_id => @site.id)
    Country.create(:name => "Suazilandia", :value => "SZ", :site_id => @site.id)
    Country.create(:name => "Suecia", :value => "SE", :site_id => @site.id)
    Country.create(:name => "Suiza", :value => "CH", :site_id => @site.id)
    Country.create(:name => "Siria", :value => "SY", :site_id => @site.id)
    Country.create(:name => "Taiwán", :value => "TW", :site_id => @site.id)
    Country.create(:name => "Tayikistán", :value => "TJ", :site_id => @site.id)
    Country.create(:name => "Tanzania", :value => "TZ", :site_id => @site.id)
    Country.create(:name => "Tailandia", :value => "TH", :site_id => @site.id)
    Country.create(:name => "Togo", :value => "TG", :site_id => @site.id)
    Country.create(:name => "Islas Tokelau", :value => "TK", :site_id => @site.id)
    Country.create(:name => "Tonga", :value => "TO", :site_id => @site.id)
    Country.create(:name => "Trinidad y Tobago", :value => "TT", :site_id => @site.id)
    Country.create(:name => "Túnez", :value => "TN", :site_id => @site.id)
    Country.create(:name => "Turquía", :value => "TR", :site_id => @site.id)
    Country.create(:name => "Turkmenistán", :value => "TC", :site_id => @site.id)
    Country.create(:name => "Islas Turks y Caicos", :value => "TV", :site_id => @site.id)
    Country.create(:name => "Tuvalu", :value => "TV", :site_id => @site.id)
    Country.create(:name => "Uganda", :value => "UG", :site_id => @site.id)
    Country.create(:name => "Ucrania", :value => "UA", :site_id => @site.id)
    Country.create(:name => "Emiratos Árabes Unidos", :value => "AE", :site_id => @site.id)
    Country.create(:name => "Reino Unido", :value => "UK", :site_id => @site.id)
    Country.create(:name => "Estados Unidos", :value => "US", :site_id => @site.id)
    Country.create(:name => "Islas menores de Estados Unidos", :value => "UM", :site_id => @site.id)
    Country.create(:name => "Uruguay", :value => "UY", :site_id => @site.id)
    Country.create(:name => "Uzbekistán", :value => "UZ", :site_id => @site.id)
    Country.create(:name => "Vanuatu", :value => "VU", :site_id => @site.id)
    Country.create(:name => "Ciudad del Vaticano", :value => "VA", :site_id => @site.id)
    Country.create(:name => "Venezuela", :value => "VE", :site_id => @site.id)
    Country.create(:name => "Vietnam", :value => "VN", :site_id => @site.id)
    Country.create(:name => "Islas Vírgenes (Reino Unido)", :value => "VG", :site_id => @site.id)
    Country.create(:name => "Islas Vírgenes (EE.UU.)", :value => "VI", :site_id => @site.id)
    Country.create(:name => "Islas Wallis y Futuna", :value => "WF", :site_id => @site.id)
    Country.create(:name => "Yemen", :value => "YE", :site_id => @site.id)
    Country.create(:name => "Yugoslavia", :value => "YU", :site_id => @site.id)
    Country.create(:name => "Zambia", :value => "ZM", :site_id => @site.id)
    Country.create(:name => "Zimbabue", :value => "ZW", :site_id => @site.id)
      
    
    # Creación de la tabla provincias y las provincias asociadas
    
    create_table :provinces, :force => true do |t|
      t.column :name, :string
      t.column :country_id, :integer
      t.column :cached_slug, :string
      t.timestamps
    end
    
    @country = Country.where(:name => "España").first
    
    Province.create(:name => "Álava", :country_id => @country.id)
    Province.create(:name => "Albacete", :country_id => @country.id)
    Province.create(:name => "Alicante", :country_id => @country.id)
    Province.create(:name => "Almería", :country_id => @country.id)
    Province.create(:name => "Asturias", :country_id => @country.id)
    Province.create(:name => "Ávila", :country_id => @country.id)
    Province.create(:name => "Badajoz", :country_id => @country.id)
    Province.create(:name => "Barcelona", :country_id => @country.id)
    Province.create(:name => "Burgos", :country_id => @country.id)
    Province.create(:name => "Cáceres", :country_id => @country.id)
    Province.create(:name => "Cádiz", :country_id => @country.id)
    Province.create(:name => "Cantabria", :country_id => @country.id)
    Province.create(:name => "Castellón", :country_id => @country.id)
    Province.create(:name => "Ciudad Real", :country_id => @country.id)
    Province.create(:name => "Córdoba", :country_id => @country.id)
    Province.create(:name => "La Coruña", :country_id => @country.id)
    Province.create(:name => "Cuenca", :country_id => @country.id)
    Province.create(:name => "Gerona", :country_id => @country.id)
    Province.create(:name => "Granada", :country_id => @country.id)
    Province.create(:name => "Guadalajara", :country_id => @country.id)
    Province.create(:name => "Guipúzcoa", :country_id => @country.id)
    Province.create(:name => "Huelva", :country_id => @country.id)
    Province.create(:name => "Huesca", :country_id => @country.id)
    Province.create(:name => "Islas Baleares", :country_id => @country.id)
    Province.create(:name => "Jaén", :country_id => @country.id)
    Province.create(:name => "León", :country_id => @country.id)
    Province.create(:name => "Lérida", :country_id => @country.id)
    Province.create(:name => "Lugo", :country_id => @country.id)
    Province.create(:name => "Madrid", :country_id => @country.id)
    Province.create(:name => "Málaga", :country_id => @country.id)
    Province.create(:name => "Murcia", :country_id => @country.id)
    Province.create(:name => "Navarra", :country_id => @country.id)
    Province.create(:name => "Orense", :country_id => @country.id)
    Province.create(:name => "Palencia", :country_id => @country.id)
    Province.create(:name => "Las Palmas", :country_id => @country.id)
    Province.create(:name => "Pontevedra", :country_id => @country.id)
    Province.create(:name => "La Rioja", :country_id => @country.id)
    Province.create(:name => "Salamanca", :country_id => @country.id)
    Province.create(:name => "Segovia", :country_id => @country.id)
    Province.create(:name => "Sevilla", :country_id => @country.id)
    Province.create(:name => "Soria", :country_id => @country.id)
    Province.create(:name => "Tarragona", :country_id => @country.id)
    Province.create(:name => "Santa Cruz de Tenerife", :country_id => @country.id)
    Province.create(:name => "Teruel", :country_id => @country.id)
    Province.create(:name => "Toledo", :country_id => @country.id)
    Province.create(:name => "Valencia", :country_id => @country.id)
    Province.create(:name => "Valladolid", :country_id => @country.id)
    Province.create(:name => "Vizcaya", :country_id => @country.id)
    Province.create(:name => "Zamora", :country_id => @country.id)
    Province.create(:name => "Zaragoza", :country_id => @country.id)
  end

  def self.down
    drop_table :provinces
    drop_table :countries
  end
end
