#encoding: utf-8

class CreateCountries < ActiveRecord::Migration

  def self.up
    create_table :countries, :force => true do |t|
      t.column :name, :string
      t.column :value, :string, :limit => 3
      t.column :cached_slug, :string
      t.timestamps
    end

    Country.create(:name => "Afganistán", :value => "AF")
    Country.create(:name => "Albania", :value => "AL")
    Country.create(:name => "Argelia", :value => "DZ")
    Country.create(:name => "Samoa Americana", :value => "AS")
    Country.create(:name => "Andorra", :value => "AD")
    Country.create(:name => "Angola", :value => "AO")
    Country.create(:name => "Anguilla", :value => "AI")
    Country.create(:name => "Antártida", :value => "AQ")
    Country.create(:name => "Antigua y Barbuda", :value => "AG")
    Country.create(:name => "Argentina", :value => "AR")
    Country.create(:name => "Armenia", :value => "AM")
    Country.create(:name => "Aruba", :value => "AW")
    Country.create(:name => "Australia", :value => "AU")
    Country.create(:name => "Austria", :value => "AT")
    Country.create(:name => "Azerbaiyán", :value => "AZ")
    Country.create(:name => "Bahamas", :value => "BS")
    Country.create(:name => "Bahrein", :value => "BH")
    Country.create(:name => "Bangladesh", :value => "BD")
    Country.create(:name => "Barbados", :value => "BB")
    Country.create(:name => "Bielorrusia", :value => "BY")
    Country.create(:name => "Bélgica", :value => "BE")
    Country.create(:name => "Belice", :value => "BZ")
    Country.create(:name => "Benin", :value => "BJ")
    Country.create(:name => "Bermudas", :value => "BM")
    Country.create(:name => "Bután", :value => "BT")
    Country.create(:name => "Bolivia", :value => "BO")
    Country.create(:name => "Bosnia y Herzegovina", :value => "BA")
    Country.create(:name => "Botswana", :value => "BW")
    Country.create(:name => "Isla Bouvet", :value => "BV")
    Country.create(:name => "Brasil", :value => "BR")
    Country.create(:name => "Territorios británicos del océano Índico", :value => "IO")
    Country.create(:name => "Brunei", :value => "BN")
    Country.create(:name => "Bulgaria", :value => "BG")
    Country.create(:name => "Burkina Faso", :value => "BF")
    Country.create(:name => "Burundi", :value => "BI")
    Country.create(:name => "Camboya", :value => "KH")
    Country.create(:name => "Camerún", :value => "CM")
    Country.create(:name => "Canadá", :value => "CA")
    Country.create(:name => "Cabo Verde", :value => "CV")
    Country.create(:name => "Islas Caimán", :value => "KY")
    Country.create(:name => "República Centroafricana", :value => "CF")
    Country.create(:name => "Chad", :value => "TD")
    Country.create(:name => "Chile", :value => "CL")
    Country.create(:name => "China", :value => "CN")
    Country.create(:name => "Isla de Christmas", :value => "CX")
    Country.create(:name => "Islas de Cocos o Keeling", :value => "CC")
    Country.create(:name => "Colombia", :value => "CO")
    Country.create(:name => "Comores", :value => "KM")
    Country.create(:name => "Congo", :value => "CG")
    Country.create(:name => "Congo, República Democrática del", :value => "CD")
    Country.create(:name => "Islas Cook", :value => "CK")
    Country.create(:name => "Costa Rica", :value => "CR")
    Country.create(:name => "Costa de Marfíl", :value => "CI")
    Country.create(:name => "Croacia", :value => "HR")
    Country.create(:name => "Cuba", :value => "CU")
    Country.create(:name => "Chipre", :value => "CY")
    Country.create(:name => "República Checa", :value => "CZ")
    Country.create(:name => "Dinamarca", :value => "DK")
    Country.create(:name => "Djibouti", :value => "DJ")
    Country.create(:name => "Dominica", :value => "DM")
    Country.create(:name => "República Dominicana", :value => "DO")
    Country.create(:name => "Timor Oriental", :value => "TP")
    Country.create(:name => "Ecuador", :value => "EC")
    Country.create(:name => "Egipto", :value => "EG")
    Country.create(:name => "El Salvador", :value => "SV")
    Country.create(:name => "Guinea Ecuatorial", :value => "GQ")
    Country.create(:name => "Eritrea", :value => "ER")
    Country.create(:name => "Estonia", :value => "EE")
    Country.create(:name => "Etiopía", :value => "ET")
    Country.create(:name => "Islas Malvinas", :value => "FK")
    Country.create(:name => "Islas Faroe", :value => "FO")
    Country.create(:name => "Fiji", :value => "FJ")
    Country.create(:name => "Finlandia", :value => "FI")
    Country.create(:name => "Francia", :value => "FR")
    Country.create(:name => "Guayana Francesa", :value => "GF")
    Country.create(:name => "Polinesia Francesa", :value => "PF")
    Country.create(:name => "Territorios franceses del Sur", :value => "TF")
    Country.create(:name => "Gabón", :value => "GA")
    Country.create(:name => "Gambia", :value => "GM")
    Country.create(:name => "Georgia", :value => "GE")
    Country.create(:name => "Alemania", :value => "DE")
    Country.create(:name => "Ghana", :value => "GH")
    Country.create(:name => "Gibraltar", :value => "GI")
    Country.create(:name => "Grecia", :value => "GR")
    Country.create(:name => "Groenlandia", :value => "GL")
    Country.create(:name => "Granada", :value => "GD")
    Country.create(:name => "Guadalupe", :value => "GP")
    Country.create(:name => "Guam", :value => "GU")
    Country.create(:name => "Guatemala", :value => "GT")
    Country.create(:name => "Guinea", :value => "GN")
    Country.create(:name => "Guinea-Bissau", :value => "GW")
    Country.create(:name => "Guayana", :value => "GY")
    Country.create(:name => "Haití", :value => "HT")
    Country.create(:name => "Islas Heard y McDonald", :value => "HM")
    Country.create(:name => "Honduras", :value => "HN")
    Country.create(:name => "Hong Kong", :value => "HK")
    Country.create(:name => "Hungría", :value => "HU")
    Country.create(:name => "Islandia", :value => "IS")
    Country.create(:name => "India", :value => "IN")
    Country.create(:name => "Indonesia", :value => "ID")
    Country.create(:name => "Irán", :value => "IR")
    Country.create(:name => "Irak", :value => "IQ")
    Country.create(:name => "Irlanda", :value => "IE")
    Country.create(:name => "Israel", :value => "IK")
    Country.create(:name => "Italia", :value => "IT")
    Country.create(:name => "Jamaica", :value => "JM")
    Country.create(:name => "Japón", :value => "JP")
    Country.create(:name => "Jordania", :value => "JO")
    Country.create(:name => "Kazajistán", :value => "KZ")
    Country.create(:name => "Kenia", :value => "KE")
    Country.create(:name => "Kiribati", :value => "KI")
    Country.create(:name => "Corea", :value => "KR")
    Country.create(:name => "Corea del Norte", :value => "KP")
    Country.create(:name => "Kuwait", :value => "KW")
    Country.create(:name => "Kirguizistán", :value => "KG")
    Country.create(:name => "Laos", :value => "LA")
    Country.create(:name => "Letonia", :value => "LV")
    Country.create(:name => "Líbano", :value => "LB")
    Country.create(:name => "Lesotho", :value => "LS")
    Country.create(:name => "Liberia", :value => "LR")
    Country.create(:name => "Libia", :value => "LY")
    Country.create(:name => "Liechtenstein", :value => "LI")
    Country.create(:name => "Lituania", :value => "LT")
    Country.create(:name => "Luxemburgo", :value => "LI")
    Country.create(:name => "Macao", :value => "MO")
    Country.create(:name => "Madagascar", :value => "MG")
    Country.create(:name => "Malawi", :value => "MW")
    Country.create(:name => "Malasia", :value => "MY")
    Country.create(:name => "Maldivas", :value => "MV")
    Country.create(:name => "Malí", :value => "ML")
    Country.create(:name => "Islas Marshall", :value => "MT")
    Country.create(:name => "Martinica", :value => "MQ")
    Country.create(:name => "Mauritania", :value => "MR")
    Country.create(:name => "Mauricio", :value => "MU")
    Country.create(:name => "Mayotte", :value => "YT")
    Country.create(:name => "México", :value => "MX")
    Country.create(:name => "Micronesia", :value => "FM")
    Country.create(:name => "Moldavia", :value => "MD")
    Country.create(:name => "Mónaco", :value => "MC")
    Country.create(:name => "Mongolia", :value => "MN")
    Country.create(:name => "Montserrat", :value => "MS")
    Country.create(:name => "Marruecos", :value => "MA")
    Country.create(:name => "Mozambique", :value => "MZ")
    Country.create(:name => "Birmania", :value => "MM")
    Country.create(:name => "Namibia", :value => "NA")
    Country.create(:name => "Nauru", :value => "NR")
    Country.create(:name => "Nepal", :value => "NP")
    Country.create(:name => "Antillas Holandesas", :value => "AN")
    Country.create(:name => "Países Bajos", :value => "NL")
    Country.create(:name => "Nueva Caledonia", :value => "NC")
    Country.create(:name => "Nueva Zelanda", :value => "NZ")
    Country.create(:name => "Nicaragua", :value => "NI")
    Country.create(:name => "Níger", :value => "NE")
    Country.create(:name => "Nigeria", :value => "NG")
    Country.create(:name => "Niue", :value => "NU")
    Country.create(:name => "Norfolk", :value => "NF")
    Country.create(:name => "Islas Marianas del Norte", :value => "MP")
    Country.create(:name => "Noruega", :value => "NO")
    Country.create(:name => "Omán", :value => "OM")
    Country.create(:name => "Paquistán", :value => "PK")
    Country.create(:name => "Islas Palau", :value => "PW")
    Country.create(:name => "Panamá", :value => "PA")
    Country.create(:name => "Papúa Nueva Guinea", :value => "PG")
    Country.create(:name => "Paraguay", :value => "PY")
    Country.create(:name => "Perú", :value => "PE")
    Country.create(:name => "Filipinas", :value => "PH")
    Country.create(:name => "Pitcairn", :value => "PN")
    Country.create(:name => "Polonia", :value => "PL")
    Country.create(:name => "Portugal", :value => "PT")
    Country.create(:name => "Puerto Rico", :value => "PR")
    Country.create(:name => "Qatar", :value => "QA")
    Country.create(:name => "Reunión", :value => "RE")
    Country.create(:name => "Rumania", :value => "RO")
    Country.create(:name => "Rusia", :value => "RU")
    Country.create(:name => "Ruanda", :value => "RW")
    Country.create(:name => "Santa Helena", :value => "SH")
    Country.create(:name => "Saint Kitts y Nevis", :value => "KN")
    Country.create(:name => "Santa Lucía", :value => "LC")
    Country.create(:name => "St. Pierre y Miquelon", :value => "PM")
    Country.create(:name => "San Vicente y Granadinas", :value => "VC")
    Country.create(:name => "Samoa", :value => "WS")
    Country.create(:name => "San Marino", :value => "SM")
    Country.create(:name => "Santo Tomé y Príncipe", :value => "ST")
    Country.create(:name => "Arabia Saudí", :value => "SA")
    Country.create(:name => "Senegal", :value => "SN")
    Country.create(:name => "Seychelles", :value => "SC")
    Country.create(:name => "Sierra Leona", :value => "SL")
    Country.create(:name => "Singapur", :value => "SG")
    Country.create(:name => "República Eslovaca", :value => "SK")
    Country.create(:name => "Eslovenia", :value => "SI")
    Country.create(:name => "Islas Salomón", :value => "SB")
    Country.create(:name => "Somalia", :value => "SO")
    Country.create(:name => "República de Sudáfrica", :value => "ZA")
    Country.create(:name => "España", :value => "ES")
    Country.create(:name => "Sri Lanka", :value => "LK")
    Country.create(:name => "Sudán", :value => "SD")
    Country.create(:name => "Surinam", :value => "SR")
    Country.create(:name => "Islas Svalbard y Jan Mayen", :value => "SJ")
    Country.create(:name => "Suazilandia", :value => "SZ")
    Country.create(:name => "Suecia", :value => "SE")
    Country.create(:name => "Suiza", :value => "CH")
    Country.create(:name => "Siria", :value => "SY")
    Country.create(:name => "Taiwán", :value => "TW")
    Country.create(:name => "Tayikistán", :value => "TJ")
    Country.create(:name => "Tanzania", :value => "TZ")
    Country.create(:name => "Tailandia", :value => "TH")
    Country.create(:name => "Togo", :value => "TG")
    Country.create(:name => "Islas Tokelau", :value => "TK")
    Country.create(:name => "Tonga", :value => "TO")
    Country.create(:name => "Trinidad y Tobago", :value => "TT")
    Country.create(:name => "Túnez", :value => "TN")
    Country.create(:name => "Turquía", :value => "TR")
    Country.create(:name => "Turkmenistán", :value => "TC")
    Country.create(:name => "Islas Turks y Caicos", :value => "TV")
    Country.create(:name => "Tuvalu", :value => "TV")
    Country.create(:name => "Uganda", :value => "UG")
    Country.create(:name => "Ucrania", :value => "UA")
    Country.create(:name => "Emiratos Árabes Unidos", :value => "AE")
    Country.create(:name => "Reino Unido", :value => "UK")
    Country.create(:name => "Estados Unidos", :value => "US")
    Country.create(:name => "Islas menores de Estados Unidos", :value => "UM")
    Country.create(:name => "Uruguay", :value => "UY")
    Country.create(:name => "Uzbekistán", :value => "UZ")
    Country.create(:name => "Vanuatu", :value => "VU")
    Country.create(:name => "Ciudad del Vaticano", :value => "VA")
    Country.create(:name => "Venezuela", :value => "VE")
    Country.create(:name => "Vietnam", :value => "VN")
    Country.create(:name => "Islas Vírgenes (Reino Unido)", :value => "VG")
    Country.create(:name => "Islas Vírgenes (EE.UU.)", :value => "VI")
    Country.create(:name => "Islas Wallis y Futuna", :value => "WF")
    Country.create(:name => "Yemen", :value => "YE")
    Country.create(:name => "Yugoslavia", :value => "YU")
    Country.create(:name => "Zambia", :value => "ZM")
    Country.create(:name => "Zimbabue", :value => "ZW")
      
    
    # Creación de la tabla provincias y las provincias asociadas
    
    create_table :provinces, :force => true do |t|
      t.column :name, :string
      t.column :country_id, :integer
      t.column :cached_slug, :string
      t.timestamps
    end
    
    @country = Country.where(:name => "España").first
    
    Province.create(:name => "Álava", :country_id => @country.id)
    Province.create(:name => "Albacete", :country_id => @country.id)
    Province.create(:name => "Alicante", :country_id => @country.id)
    Province.create(:name => "Almería", :country_id => @country.id)
    Province.create(:name => "Asturias", :country_id => @country.id)
    Province.create(:name => "Ávila", :country_id => @country.id)
    Province.create(:name => "Badajoz", :country_id => @country.id)
    Province.create(:name => "Barcelona", :country_id => @country.id)
    Province.create(:name => "Burgos", :country_id => @country.id)
    Province.create(:name => "Cáceres", :country_id => @country.id)
    Province.create(:name => "Cádiz", :country_id => @country.id)
    Province.create(:name => "Cantabria", :country_id => @country.id)
    Province.create(:name => "Castellón", :country_id => @country.id)
    Province.create(:name => "Ciudad Real", :country_id => @country.id)
    Province.create(:name => "Córdoba", :country_id => @country.id)
    Province.create(:name => "La Coruña", :country_id => @country.id)
    Province.create(:name => "Cuenca", :country_id => @country.id)
    Province.create(:name => "Gerona", :country_id => @country.id)
    Province.create(:name => "Granada", :country_id => @country.id)
    Province.create(:name => "Guadalajara", :country_id => @country.id)
    Province.create(:name => "Guipúzcoa", :country_id => @country.id)
    Province.create(:name => "Huelva", :country_id => @country.id)
    Province.create(:name => "Huesca", :country_id => @country.id)
    Province.create(:name => "Islas Baleares", :country_id => @country.id)
    Province.create(:name => "Jaén", :country_id => @country.id)
    Province.create(:name => "León", :country_id => @country.id)
    Province.create(:name => "Lérida", :country_id => @country.id)
    Province.create(:name => "Lugo", :country_id => @country.id)
    Province.create(:name => "Madrid", :country_id => @country.id)
    Province.create(:name => "Málaga", :country_id => @country.id)
    Province.create(:name => "Murcia", :country_id => @country.id)
    Province.create(:name => "Navarra", :country_id => @country.id)
    Province.create(:name => "Orense", :country_id => @country.id)
    Province.create(:name => "Palencia", :country_id => @country.id)
    Province.create(:name => "Las Palmas", :country_id => @country.id)
    Province.create(:name => "Pontevedra", :country_id => @country.id)
    Province.create(:name => "La Rioja", :country_id => @country.id)
    Province.create(:name => "Salamanca", :country_id => @country.id)
    Province.create(:name => "Segovia", :country_id => @country.id)
    Province.create(:name => "Sevilla", :country_id => @country.id)
    Province.create(:name => "Soria", :country_id => @country.id)
    Province.create(:name => "Tarragona", :country_id => @country.id)
    Province.create(:name => "Santa Cruz de Tenerife", :country_id => @country.id)
    Province.create(:name => "Teruel", :country_id => @country.id)
    Province.create(:name => "Toledo", :country_id => @country.id)
    Province.create(:name => "Valencia", :country_id => @country.id)
    Province.create(:name => "Valladolid", :country_id => @country.id)
    Province.create(:name => "Vizcaya", :country_id => @country.id)
    Province.create(:name => "Zamora", :country_id => @country.id)
    Province.create(:name => "Zaragoza", :country_id => @country.id)
  end

  def self.down
    drop_table :provinces
    drop_table :countries
  end
end
